services:
  nginx:
    image: nginx:1.28.0-alpine
    container_name: todo-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      # Sample static HTML
      # - ./prior-tests:/usr/share/nginx/html:ro
      # Actual front-end build files
      - ./nginx/dist:/usr/share/nginx/html:ro
    depends_on:
      - api
    networks:
      - todo-net
    restart: unless-stopped

  api:
    build:
      context: ../back-end
      dockerfile: Dockerfile.prod
    container_name: todo-sails-app
    ports:
      - "1337"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=5432
      # Node pg migrate connection string
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}
      - SESSION_HOST=session-db
      - SESSION_PORT=6379
      - SESSION_PASSWORD=${SESSION_PASSWORD}
      - SESSION_DB=0
      - SESSION_SECRET=${SESSION_SECRET}
    depends_on:
      db:
        condition: service_healthy  
      session-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:1337/api/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 30s
    networks:
      - todo-net
      - todo-back-net
    restart: unless-stopped

  db:
    image: postgres:12.21
    container_name: todo-postgres-db
    ports:
      - "5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - todo-back-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"] 
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 30s
    restart: unless-stopped

  session-db:
    image: redis:7.4.1-alpine
    container_name: todo-redis
    ports:
      - "6379"
    command: redis-server --requirepass ${SESSION_PASSWORD}
    networks:
      - todo-back-net
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${SESSION_PASSWORD} ping"]
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 30s
    restart: unless-stopped

  # Mock REST API to test reverse proxy 
  # api:
  #   image: clue/json-server
  #   container_name: api-server
  #   volumes:
  #     - ./prior-tests/sample-api.json:/data/db.json
  #   restart: unless-stopped

volumes:
  postgres-data:

networks:
  todo-back-net:
    driver: bridge
  todo-net:
    external: true


