# Create network:
# docker network create todo-net

services:
  api:
    build:
      dockerfile: Dockerfile
    container_name: todo-sails-app
    ports:
      - "1340:1337"
      - "9229:9229"
    environment:
      # - API_HOST=todo-sails-app
      # - API_PORT=1337
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=todo-db
      - DATABASE_PORT=5432
      # Node pg migrate connection string
      - DATABASE_URL=postgres://postgres:postgres@db:5432/todo-db
      - SESSION_HOST=session-db
      - SESSION_PORT=6379
      - SESSION_PASSWORD=todo-redis
      - SESSION_DB=0
      - SESSION_SECRET=7cf7e3ddb3e7a9c9e56f5e22939480080507889c14523043579fc15cab83c611
      - NODE_EXTRA_CA_CERTS=/usr/todo-app/config/ssl/rootCA.pem
    depends_on:
      db:
        condition: service_healthy  
      session-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:1337/ || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 30s
    networks:
      - todo-back-net
      - todo-net
    volumes:
      # Mount source code for hot reloading
      - .:/usr/todo-app 
      - /usr/todo-app/node_modules

  db:
    image: postgres:12.21
    container_name: todo-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo-db
    ports:
      - "5432:5432"
    networks:
      - todo-back-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo-db"] 
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 30s

  pgadmin:
    image: dpage/pgadmin4:8.13
    container_name: todo-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: todo@serfe.com
      PGADMIN_DEFAULT_PASSWORD: todo
    ports:
      - "5051:80"
    depends_on:
      - db
    networks:
      - todo-back-net

  session-db:
    image: redis:alpine3.20
    container_name: todo-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "todo-redis"]
    networks:
      - todo-back-net
      - todo-net
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a todo-redis ping"]
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 30s

volumes:
  postgres-data:

networks:
  todo-back-net:
    driver: bridge
  todo-net:
    external: true
